### ISSUE TITLE
Refactoring tasks

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#230]
This issue contains refactoring tasks

- [ ] : don't use always ```appWallet!.appKeychain!.getAccountSelected()```
- [ ] : transfer sheet : distinct token and uco management more clearly
- [x] : transform main screen pageview in widgets
- [ ] : centralise waitConfirmations management
- [ ] : mutualize _launchSecurityConfiguration
- [x] : externalize _balanceNetwork
- [ ] : improve separate between view and controller.
- [ ] : carriage return for long String
- [ ] : improve amount display management
- [ ] : Merge ownership management
- [ ] : add show in import

**Comment by redDwarf03** [comment]
To many codes written since this issue
